### ISSUE TITLE
memory and time limit exceeded

### ISSUE THREAD

**Issue by makapoh** [klas/LanternFish#16]
Hi! we use lanternfish 1.3.8 on joomla 3.4.6.
If i send query to site with method HEAD, i get error 500 with memory or time limit in
plugins/system/jfdatabase/intercept.jdatabasemysqli.php
function loadObjectList

if i send GET or POST request, all good.
if i disable jfdatabase plugin, all good.

**Comment by klas** [comment]
Please use ticket system on the site.
